<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="Lib.Harmony.Ref" Version="2.4.2" />
		<PackageVersion Include="PLib" Version="4.25.0" />
		<PackageVersion Include="ILRepack.Lib.MSBuild.Task" Version="2.0.46" />
		<PackageVersion Include="PolySharp" Version="1.15.0" />
	</ItemGroup>

	<!-- Test dependencies -->
	<ItemGroup>
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageVersion Include="xunit" Version="2.9.2" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
		<PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
</Project>
