using BlueprintsV2.BlueprintData;
using PeterHan.PLib.Options;

namespace BlueprintsV2;

public enum DefaultSelections
{
    [Option("STRINGS.BLUEPRINTS_CONFIG.DEFAULTMENUSELECTION.DEFAULTMENUSELECTION_ALL")]
    All,
    [Option("STRINGS.BLUEPRINTS_CONFIG.DEFAULTMENUSELECTION.DEFAULTMENUSELECTION_NONE")]
    None,
    [Option("STRINGS.UI.TOOLS.FILTERLAYERS.BUILDINGS.NAME")]
    BuildingsOnly
}

[Serializable]
[RestartRequired]
[ModInfo("https://github.com/dytterud/oni-mods", collapse: true)]
[ConfigFile(SharedConfigLocation: true)]
public class Config : SingletonOptions<Config>
{
    [Option("STRINGS.BLUEPRINTS_CONFIG.DEFAULTMENUSELECTION.TITLE", "STRINGS.BLUEPRINTS_CONFIG.DEFAULTMENUSELECTION.TOOLTIP")]
    public DefaultSelections DefaultMenuSelections { get; set; } = DefaultSelections.All;

    [Option("STRINGS.UI.TOOLS.FILTERLAYERS.BLUEPRINTV2_PLANNINGTOOL_SHAPES.NAME", "STRINGS.UI.TOOLS.FILTERLAYERS.BLUEPRINTV2_PLANNINGTOOL_SHAPES.TOOLTIP", "STRINGS.BLUEPRINTS_CONFIG.EXTRA_DEFAULTS_CATEGORY")]
    public bool DefaultCollect_PlanningToolMod_Shapes { get; set; } = true;

    [Option("STRINGS.BLUEPRINTS_CONFIG.REQUIRECONSTRUCTABLE_TECH.TITLE", "STRINGS.BLUEPRINTS_CONFIG.REQUIRECONSTRUCTABLE_TECH.TOOLTIP")]
    public bool RequireConstructable_Tech { get; set; } = true;
    [Option("STRINGS.BLUEPRINTS_CONFIG.REQUIRECONSTRUCTABLE_MATERIAL.TITLE", "STRINGS.BLUEPRINTS_CONFIG.REQUIRECONSTRUCTABLE_MATERIAL.TOOLTIP")]
    public bool RequireConstructable_Material { get; set; } = true;

    [Option("STRINGS.BLUEPRINTS_CONFIG.FXTIME.TITLE", "STRINGS.BLUEPRINTS_CONFIG.FXTIME.TOOLTIP")]
    public float FXTime { get; set; } = 4;

    [Option("STRINGS.BLUEPRINTS_CONFIG.CREATEBLUEPRINTTOOLSYNC.TITLE", "STRINGS.BLUEPRINTS_CONFIG.CREATEBLUEPRINTTOOLSYNC.TOOLTIP")]
    public bool CreateBlueprintToolSync { get; set; } = true;

    [Option("STRINGS.BLUEPRINTS_CONFIG.CREATEBLUEPRINTTOOLCOPYTOCLIPBOARD.TITLE", "STRINGS.BLUEPRINTS_CONFIG.CREATEBLUEPRINTTOOLCOPYTOCLIPBOARD.TOOLTIP")]
    public bool CreateBlueprintToolCopyToClipboard { get; set; } = false;

    [Option("STRINGS.BLUEPRINTS_CONFIG.SNAPSHOTTOOLSYNC.TITLE", "STRINGS.BLUEPRINTS_CONFIG.SNAPSHOTTOOLSYNC.TOOLTIP")]
    public bool SnapshotToolSync { get; set; } = true;

    [Option("STRINGS.BLUEPRINTS_CONFIG.SNAPSHOTTOOLCOPYTOCLIPBOARD.TITLE", "STRINGS.BLUEPRINTS_CONFIG.SNAPSHOTTOOLCOPYTOCLIPBOARD.TOOLTIP")]
    public bool SnapshotToolCopyToClipboard { get; set; } = false;

    [Option("STRINGS.BLUEPRINTS_CONFIG.AUTOPREVIEWCUTTOFF.TITLE", "STRINGS.BLUEPRINTS_CONFIG.AUTOPREVIEWCUTTOFF.TOOLTIP")]
    public int AutoPreviewCuttoff { get; set; } = 2000;
    [Option("STRINGS.BLUEPRINTS_CONFIG.DEFAULT_ANCHOR.TITLE", "STRINGS.BLUEPRINTS_CONFIG.DEFAULT_ANCHOR.TOOLTIP")]
    public BlueprintAnchorState DefaultAnchorState { get; set; } = BlueprintAnchorState.BottomCenter;
}
